services:
  mosquitto:
    build:
      context: .
      args:
        - USER=mqtt
        - GID=1001
        - UID=1002
    volumes:
      # - type: bind
        # source: ./config/
        # target: /mosquitto/config/
      # - type: bind
        # source: ./log/
        # target: /mosquitto/log/
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - type: volume
        source: data
        target: /mosquitto/data/
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

volumes:
  data:
    name: "mqtt-broker-data"
